#!/bin/bash
cd Topologie && ./build && cd ..
cd "Calcul Différentiel I" &&  ./build && cd ..
cd "Calcul Différentiel II" &&  ./build && cd ..
cd "Calcul Intégral I" &&  ./build && cd ..
cd "Calcul Intégral II" &&  ./build && cd ..
cd "Calcul Intégral III" &&  ./build && cd ..
