#!/bin/bash
set -e
set -o pipefail

mkdir -p output

DOC="Calcul Intégral I"

# Options
OPT=(-V lang=fr)
OPT+=(--table-of-contents)

# Generate Images
cd images
./mainz.py
cd ..

# PDF Output
pandoc "${OPT[@]}" -o output/"${DOC}".pdf "${DOC}".md
