#!/bin/bash

# Build subdirs
for dir in */; do
    cd "${dir}"
    if [ -f build ]; then
        echo "build ${dir}"
        ./build
    fi
    cd ..
done

# Gather outputs
mkdir -p output
cp */output/* output