#!/bin/bash

set -e
set -o pipefail

# Build subdirs
for dir in */; do
    if [ "${dir}" != "utils/" ]; then
        cd "${dir}"
        if [ -f build ]; then
            echo "build ${dir}"
            ./build "$@"
        fi
        cd ..
    fi
done

# Gather outputs
mkdir -p output
cp -rf */output/* output