#!/bin/bash
set -e
set -o pipefail

DOC="Calcul Différentiel I"

# Doctest
python -m doctest "${DOC}.md"

# Output Directory
mkdir -p output

# Options
OPT=(-V lang=fr)
OPT+=(--table-of-contents)
OPT+=(--bibliography=bibliography.json -M link-citations=true)
OPT+=(--pdf-engine=pdflatex)

# PDF Output
pandoc "${OPT[@]}" -o output/"${DOC}".pdf "${DOC}".md
