#!/bin/bash
set -e
set -o pipefail

mkdir -p output

DOC="Dossier Pédagogique"

# Options
OPT=(-V lang=fr)
OPT+=(--table-of-contents)
OPT+=(--standalone)
OPT+=(--bibliography=bibliography.json -M link-citations=true)

# Outputs
pandoc "${OPT[@]}" -o "output/${DOC}.pdf" "${DOC}.md"
pandoc "${OPT[@]}" -o "output/${DOC}.odt" "${DOC}.md"
pandoc "${OPT[@]}" -o "output/${DOC}.html" "${DOC}.md"

